# Generated by Django 2.2.4 on 2019-11-10 17:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCounting',
            fields=[
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userapp.Problem')),
                ('count_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='문제 카운팅 배열')),
            ],
        ),
    ]
