# Generated by Django 2.2.4 on 2019-11-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20191111_0305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemCounting',
        ),
    ]
