# Generated by Django 2.2.4 on 2019-11-10 18:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_delete_problemcounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCounting',
            fields=[
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userapp.Problem')),
                ('count_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='문제 카운팅 배열')),
            ],
            options={
                'db_table': 'tb_problem_counting',
                'ordering': ['problem_id'],
            },
        ),
    ]
