# Generated by Django 2.2.4 on 2019-11-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_problemcounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='사용자 이름'),
        ),
    ]
